blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/mihonapp/mihon/issues/new/choose
    about: Issues and requests about the app itself should be opened in the mihon repository instead
  - name: 🖥️ Mihon website
    url: https://mihon.app/help/
    about: Guides, troubleshooting, and answers to common questions
